Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Test
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: time
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: time
          AttributeType: S
